<?php /* @var $this Mouf\Controllers\RootController */ ?>
<h1>Welcome to Splash</h1>

<p>This file is your welcome page. It is generated by the RootController class and the views/root/index.php file. Please feel free to customize it.</p>