<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 * This file contains the status of all Mouf global installation processes for packages you have installed.
 * If you are working with a source repository, this file should be commited.
 */
return array (
  0 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.file-cache',
  ),
  1 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.log.errorlog_logger',
  ),
  2 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.apc-cache',
  ),
  3 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.renderer',
  ),
  4 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/html.utils.weblibrarymanager',
  ),
  5 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/javascript.jquery.jquery',
  ),
  6 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/html.utils.bootstrap',
  ),
  7 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.i18n.fine',
  ),
  8 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.session.session-manager',
  ),
  9 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.widgets.messageservice',
  ),
  10 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/html.template.bootstrap',
  ),
  11 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/validatorsInstall.php',
    'package' => 'mouf/utils.common.validators',
  ),
  12 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/splashCommonInstall.php',
    'package' => 'mouf/mvc.splash-common',
  ),
  13 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'src/install.php',
    'package' => 'mouf/utils.cache.no-cache',
  ),
  14 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splashinstall/',
    'package' => 'mouf/mvc.splash',
  ),
  15 => 
  array (
    'status' => 'done',
    'type' => 'url',
    'url' => 'splashinstall/writeHtAccess',
    'package' => 'mouf/mvc.splash',
  ),
  16 => 
  array (
    'status' => 'done',
    'type' => 'file',
    'file' => 'install.php',
    'package' => 'mouf/modules.google-analytics',
  ),
);