<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'ROOT_URL' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The ROOT_URL of the Mouf web application. This is the URL, starting and ending with a slash, that you use to access the Mouf administration interface.',
  ),
  'DB_HOST' => 
  array (
    'defaultValue' => 'localhost',
    'type' => 'string',
    'comment' => 'The database host (the IP address or URL of the database server).',
  ),
  'DB_PORT' => 
  array (
    'defaultValue' => '',
    'type' => 'int',
    'comment' => 'The database port (the port of the database server, keep empty to use default port).',
  ),
  'DB_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The name of your database.',
  ),
  'DB_USERNAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The username to access the database.',
  ),
  'DB_PASSWORD' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The password to access the database.',
  ),
  'REPOSITORY_PATH' => 
  array (
    'defaultValue' => '/var/mouf/repositories',
    'type' => 'string',
    'comment' => 'The full path to the repository containing all packages that will be downloaded. This should not end if a slash.',
  ),
  'PACKAGIST_USERNAME' => 
  array (
    'defaultValue' => 'mouf',
    'type' => 'string',
    'comment' => 'The name of the Packagist user will fetch the packages of.',
  ),
  'ROOT_DOMAIN' => 
  array (
    'defaultValue' => 'doc.mouf-php',
    'type' => 'string',
    'comment' => 'The parent domain.',
  ),
));

$moufManager->setAllVariables(array (
  'tdbmDefaultSourceDirectory' => 'src/',
  'tdbmDefaultDaoNamespace' => 'Mouf\\Dao',
  'tdbmDefaultBeanNamespace' => 'Mouf\\Dao\\Bean',
  'tdbmDefaultDaoFactoryName' => 'DaoFactory',
  'tdbmDefaultDaoFactoryInstanceName' => 'daoFactory',
  'splashDefaultSourceDirectory' => 'src/',
  'splashDefaultControllersNamespace' => 'Mouf\\Controllers\\',
  'splashDefaultViewsDirectory' => 'views/',
  'splashexludeextentions' => 
  array (
    0 => '',
  ),
  'splashexludefolders' => 
  array (
    0 => 'vendor',
  ),
));

$moufManager->addComponentInstances(array (
  '__anonymous_1359148369926' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapMenuRenderer',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'documentationMenu',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldProperties' => 
    array (
      'pills' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
      'stacked' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1359315228607' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapMenuRenderer',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous_1359315236912',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1359315236912' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'versionsMenuItem',
          1 => 'packagesMenuItem',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'ROOT_URL',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'navBar',
      ),
    ),
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => '__anonymous_1359148369926',
      ),
    ),
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
    ),
    'fieldProperties' => 
    array (
      'enableResponsiveDesign' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
    ),
  ),
  'daoFactory' => 
  array (
    'class' => 'Mouf\\Dao\\DaoFactory',
    'external' => false,
  ),
  'dbConnection' => 
  array (
    'class' => 'Mouf\\Database\\DBConnection\\MySqlConnection',
    'external' => false,
    'fieldProperties' => 
    array (
      'host' => 
      array (
        'value' => 'DB_HOST',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'port' => 
      array (
        'value' => 'DB_PORT',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'user' => 
      array (
        'value' => 'DB_USERNAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'password' => 
      array (
        'value' => 'DB_PASSWORD',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      'dbname' => 
      array (
        'value' => 'DB_NAME',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'defaultTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'jQueryLibrary',
        1 => 'javascript.bootstrap',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'documentationMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'weak' => false,
  ),
  'errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => 4,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'ROOT_URL',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
    ),
  ),
  'fineCommonTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'httpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'contentBlock' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG_MODE',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.7.2.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'javascript.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/js/bootstrap.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'navBar' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapNavBar',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'inverted' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => '__anonymous_1359315228607',
      ),
    ),
  ),
  'noCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\NoCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
    ),
  ),
  'packageExplorer' => 
  array (
    'class' => 'Mouf\\Services\\PackageExplorer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'REPOSITORY_PATH',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesInstaller' => 
  array (
    'class' => 'Mouf\\Services\\PackagesInstaller',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'config',
        'value' => 'REPOSITORY_PATH',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'Other packages',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rootController' => 
  array (
    'class' => 'Mouf\\Controllers\\RootController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'content' => 'block.content',
      'http404Handler' => 'httpErrorsController',
      'documentationMenu' => 'documentationMenu',
      'navBar' => 'navBar',
      'versionsMenuItem' => 'versionsMenuItem',
      'packagesMenuItem' => 'packagesMenuItem',
      'packageExporer' => 'packageExplorer',
    ),
    'fieldProperties' => 
    array (
      'repositoryPath' => 
      array (
        'type' => 'config',
        'value' => 'REPOSITORY_PATH',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG_MODE',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'http404Handler' => 'httpErrorsController',
      'http500Handler' => 'httpErrorsController',
      'cacheService' => 'splashCacheApc',
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'splashCacheApc' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'fallback' => 'splashCacheFile',
    ),
    'fieldProperties' => 
    array (
      'prefix' => 
      array (
        'type' => 'config',
        'value' => 'ROOT_URL',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashCacheFile' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'cacheDirectory' => 
      array (
        'value' => 'splashCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'type' => 'config',
        'value' => 'ROOT_URL',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/mvc.splash-common/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'tdbmService' => 
  array (
    'class' => 'Mouf\\Database\\TDBM\\TDBMService',
    'external' => false,
    'setterBinds' => 
    array (
      'setConnection' => 'dbConnection',
      'setCacheService' => 'noCacheService',
    ),
  ),
  'userService' => 
  array (
    'class' => 'Mouf\\Security\\UserService\\UserService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
    ),
  ),
  'versionsMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'Browse version',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));


unset($moufManager);

/**
				* This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
				* This object can be used to get the objects manage by MOUF.
				*
				*/
				class Mouf {
					/**
	 * @return Mouf\Html\Template\Menus\BootstrapMenuRenderer
	 */
	 public static function get__anonymous_1359148369926() {
	 	return MoufManager::getMoufManager()->getInstance('__anonymous_1359148369926');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BootstrapMenuRenderer
	 */
	 public static function get__anonymous_1359315228607() {
	 	return MoufManager::getMoufManager()->getInstance('__anonymous_1359315228607');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function get__anonymous_1359315236912() {
	 	return MoufManager::getMoufManager()->getInstance('__anonymous_1359315236912');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->getInstance('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->getInstance('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->getInstance('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->getInstance('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->getInstance('block.right');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->getInstance('bootstrapTemplate');
	 }

	/**
	 * @return Mouf\Dao\DaoFactory
	 */
	 public static function getDaoFactory() {
	 	return MoufManager::getMoufManager()->getInstance('daoFactory');
	 }

	/**
	 * @return Mouf\Database\DBConnection\MySqlConnection
	 */
	 public static function getDbConnection() {
	 	return MoufManager::getMoufManager()->getInstance('dbConnection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getDefaultLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('defaultLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getDefaultTranslationService() {
	 	return MoufManager::getMoufManager()->getInstance('defaultTranslationService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->getInstance('defaultWebLibraryRenderer');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getDocumentationMenu() {
	 	return MoufManager::getMoufManager()->getInstance('documentationMenu');
	 }

	/**
	 * @return Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogLogger() {
	 	return MoufManager::getMoufManager()->getInstance('errorLogLogger');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('fileCacheService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getFineCommonTranslationService() {
	 	return MoufManager::getMoufManager()->getInstance('fineCommonTranslationService');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getHttpErrorsController() {
	 	return MoufManager::getMoufManager()->getInstance('httpErrorsController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->getInstance('jQueryLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_bootstrap() {
	 	return MoufManager::getMoufManager()->getInstance('javascript.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BootstrapNavBar
	 */
	 public static function getNavBar() {
	 	return MoufManager::getMoufManager()->getInstance('navBar');
	 }

	/**
	 * @return Mouf\Utils\Cache\NoCache
	 */
	 public static function getNoCacheService() {
	 	return MoufManager::getMoufManager()->getInstance('noCacheService');
	 }

	/**
	 * @return Mouf\Services\PackageExplorer
	 */
	 public static function getPackageExplorer() {
	 	return MoufManager::getMoufManager()->getInstance('packageExplorer');
	 }

	/**
	 * @return Mouf\Services\PackagesInstaller
	 */
	 public static function getPackagesInstaller() {
	 	return MoufManager::getMoufManager()->getInstance('packagesInstaller');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getPackagesMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('packagesMenuItem');
	 }

	/**
	 * @return Mouf\Controllers\RootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->getInstance('rootController');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->getInstance('splash');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->getInstance('splashBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getSplashCacheApc() {
	 	return MoufManager::getMoufManager()->getInstance('splashCacheApc');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getSplashCacheFile() {
	 	return MoufManager::getMoufManager()->getInstance('splashCacheFile');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->getInstance('splashTranslateService');
	 }

	/**
	 * @return Mouf\Database\TDBM\TDBMService
	 */
	 public static function getTdbmService() {
	 	return MoufManager::getMoufManager()->getInstance('tdbmService');
	 }

	/**
	 * @return Mouf\Security\UserService\UserService
	 */
	 public static function getUserService() {
	 	return MoufManager::getMoufManager()->getInstance('userService');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getVersionsMenuItem() {
	 	return MoufManager::getMoufManager()->getInstance('versionsMenuItem');
	 }

}
?>
