<?php
/**
 * This is a file automatically generated by the Mouf framework. Do not modify it, as it could be overwritten.
 */
use Mouf\MoufManager;
use Interop\Container\ContainerInterface;
MoufManager::initMoufManager();
$moufManager = MoufManager::getMoufManager();

$moufManager->getConfigManager()->setConstantsDefinitionArray(array (
  'REPOSITORY_PATH' => 
  array (
    'defaultValue' => '/var/mouf/repositories',
    'type' => 'string',
    'comment' => 'The full path to the repository containing all packages that will be downloaded. This should not end if a slash.',
  ),
  'PACKAGIST_USERNAME' => 
  array (
    'defaultValue' => 'mouf',
    'type' => 'string',
    'comment' => 'The name of the Packagist user will fetch the packages of.',
  ),
  'ROOT_DOMAIN' => 
  array (
    'defaultValue' => 'doc.mouf-php',
    'type' => 'string',
    'comment' => 'The parent domain.',
  ),
  'DEBUG_MODE' => 
  array (
    'defaultValue' => '0',
    'type' => 'string',
    'comment' => '',
  ),
  'STARRED_PACKAGES' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'A list of packages that should be "starred" on the homepage. The package name should not contain the owner (for instance, your write "mypackage" instead of "me/mypackage", and if there are several packages, they should be separated with ;',
  ),
  'GOOGLE_ANALYTICS_KEY' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'Your Google Analytics key. Leave empty if you want to disable Google Analytics tracking. Don\'t have a key for your website? Get one here: http://www.google.com/analytics/',
  ),
  'GOOGLE_ANALYTICS_DOMAIN_NAME' => 
  array (
    'defaultValue' => '',
    'type' => 'string',
    'comment' => 'The base domain name to track (if you are tracking sub-domains). In the form: \'.example.com\'. Keep this empty if you don\'t track subdomains.',
  ),
  'DEBUG' => 
  array (
    'defaultValue' => true,
    'type' => 'bool',
    'comment' => 'Set to true to enable debug/development mode.',
  ),
  'SECRET' => 
  array (
    'defaultValue' => 'RieoqwQfpdcWjuvi4UuG',
    'type' => 'string',
    'comment' => 'A random string. It should be different for any application deployed.',
  ),
));

$moufManager->setAllVariables(array (
  'tdbmDefaultSourceDirectory' => 'src/',
  'tdbmDefaultDaoNamespace' => 'Mouf\\Dao',
  'tdbmDefaultBeanNamespace' => 'Mouf\\Dao\\Bean',
  'tdbmDefaultDaoFactoryName' => 'DaoFactory',
  'tdbmDefaultDaoFactoryInstanceName' => 'daoFactory',
  'splashDefaultSourceDirectory' => 'src/',
  'splashDefaultControllersNamespace' => 'Mouf\\Controllers\\',
  'splashDefaultViewsDirectory' => 'views/',
  'splashexludeextentions' => 
  array (
    0 => '',
  ),
  'splashexludefolders' => 
  array (
    0 => 'vendor',
  ),
));

$moufManager->addComponentInstances(array (
  '__anonymous_1359315228607' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapMenuRenderer',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => '__anonymous_1359315236912',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1359315236912' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'versionsMenuItem',
          1 => 'packagesMenuItem',
          2 => 'learnMenuItem',
          3 => 'homeMenuItem',
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1360168489288' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\InlineWebLibrary',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'setterProperties' => 
    array (
      'setJSFromText' => 
      array (
        'type' => 'string',
        'value' => '<script type="text/javascript">hljs.initHighlightingOnLoad();</script>',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1363619493475' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'setterProperties' => 
    array (
      'setCssFiles' => 
      array (
        'value' => 
        array (
          0 => 'src/views/styles.css',
        ),
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  '__anonymous_1364234789150' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BasicMenuRenderer',
    'external' => false,
    'weak' => true,
    'anonymous' => true,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'documentationMenu',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldProperties' => 
    array (
      'cssClass' => 
      array (
        'type' => 'string',
        'value' => 'nav  nav-pills nav-stacked',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'apcCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
      'fallback' => 'fileCacheService',
    ),
  ),
  'block.content' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
    ),
    'fieldProperties' => 
    array (
    ),
  ),
  'block.footer' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.header' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'navBar',
      ),
    ),
  ),
  'block.left' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => 'block.logoHolder',
        1 => '__anonymous_1364234789150',
      ),
    ),
  ),
  'block.logoHolder' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'block.right' => 
  array (
    'class' => 'Mouf\\Html\\HtmlElement\\HtmlBlock',
    'external' => false,
    'weak' => false,
  ),
  'bootstrapRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.template.bootstrap/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'template',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'bootstrapTemplate' => 
  array (
    'class' => 'Mouf\\Html\\Template\\BootstrapTemplate',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setContent' => 'block.content',
      'setLeft' => 'block.left',
      'setRight' => 'block.right',
      'setHeader' => 'block.header',
      'setFooter' => 'block.footer',
      'setWebLibraryManager' => 'defaultWebLibraryManager',
      'setDefaultRenderer' => 'defaultRenderer',
      'setTemplateRenderer' => 'bootstrapRenderer',
    ),
    'fieldProperties' => 
    array (
      'enableResponsiveDesign' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterProperties' => 
    array (
      'setLeftColumnSize' => 
      array (
        'type' => 'string',
        'value' => '3',
        'metadata' => 
        array (
        ),
      ),
      'setWrapLeftSideBarInWell' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'customRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'custom',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'daoFactory' => 
  array (
    'class' => 'Mouf\\Dao\\DaoFactory',
    'external' => false,
  ),
  'defaultLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'defaultRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\AutoChainRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'defaultTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
  ),
  'defaultWebLibraryManager' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibraryManager',
    'external' => false,
    'setterBinds' => 
    array (
      'setWebLibraries' => 
      array (
        0 => 'jQueryLibrary',
        1 => 'javascript.bootstrap',
        2 => 'javascript.highlight.js',
        3 => '__anonymous_1360168489288',
        4 => '__anonymous_1363619493475',
        5 => 'googleAnalyticsWebLibrary',
        6 => 'messageServiceLibrary',
      ),
    ),
  ),
  'defaultWebLibraryRenderer' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\DefaultWebLibraryRenderer',
    'external' => false,
  ),
  'documentationMenu' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\Menu',
    'external' => false,
    'weak' => false,
  ),
  'emailValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\EmailValidator',
    'external' => false,
    'weak' => false,
  ),
  'errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'level' => 
      array (
        'value' => 4,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'exceptionRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\ExceptionRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'phpVarsCheckRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'httpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'fileCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'defaultTimeToLive' => 
      array (
        'value' => 3600,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'value' => 'SECRET',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
    ),
  ),
  'fineCommonTranslationService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'defaultLanguageDetection',
    ),
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.i18n.fine/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'googleAnalyticsWebLibrary' => 
  array (
    'class' => 'Mouf\\Modules\\GoogleAnalytics\\GoogleAnalyticsWebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'GOOGLE_ANALYTICS_KEY',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'GOOGLE_ANALYTICS_DOMAIN_NAME',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'homeMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Home',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'http://mouf-php.com',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'homePageController' => 
  array (
    'class' => 'Mouf\\Controllers\\HomePageController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'content' => 'block.content',
      'documentationMenu' => 'documentationMenu',
      'navBar' => 'navBar',
      'versionsMenuItem' => 'versionsMenuItem',
      'packagesMenuItem' => 'packagesMenuItem',
      'packageExporer' => 'packageExplorer',
      'twig' => 'twigEnvironment',
      'sectionBuilder' => 'sectionBuilder',
      'pageDisplayer' => 'pageDsiplayer',
    ),
    'fieldProperties' => 
    array (
      'repositoryPath' => 
      array (
        'type' => 'config',
        'value' => 'REPOSITORY_PATH',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'httpErrorsController' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Controllers\\HttpErrorsController',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'contentBlock' => 'block.content',
    ),
    'fieldProperties' => 
    array (
      'debugMode' => 
      array (
        'value' => 'DEBUG_MODE',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'jQueryLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/javascript.jquery.jquery/jquery-1.11.0.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'javascript.bootstrap' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/js/bootstrap.min.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.utils.bootstrap/css/bootstrap.min.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'javascript.highlight.js' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
          0 => 'javascript/highlight.js/highlight.pack.js',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'javascript/highlight.js/styles/googlecode.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'learnMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'Learn',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'http://mouf-php.com/skills',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'messageServiceLibrary' => 
  array (
    'class' => 'Mouf\\Html\\Utils\\WebLibraryManager\\WebLibrary',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 
        array (
          0 => 'vendor/mouf/html.widgets.messageservice/messages.css',
        ),
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setRenderer' => 'defaultWebLibraryRenderer',
    ),
  ),
  'messageWidget' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Widget\\MessageWidget',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'messageProvider' => 'userMessageService',
    ),
  ),
  'navBar' => 
  array (
    'class' => 'Mouf\\Html\\Template\\Menus\\BootstrapNavBar',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'inverted' => 
      array (
        'type' => 'string',
        'value' => true,
        'metadata' => 
        array (
        ),
      ),
    ),
    'fieldBinds' => 
    array (
      'children' => 
      array (
        0 => '__anonymous_1359315228607',
      ),
    ),
  ),
  'noCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\NoCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'log' => 'errorLogLogger',
    ),
  ),
  'notFoundRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\NotFoundRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'httpErrorsController',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'numericValidatorDecimals' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\NumericValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowDecimals' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageExplorer' => 
  array (
    'class' => 'Mouf\\Services\\PackageExplorer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'REPOSITORY_PATH',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packageRenderer_mouf/html.widgets.messageservice' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\FileBasedRenderer',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'vendor/mouf/html.widgets.messageservice/src/templates',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'rendererCacheService',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'package',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      3 => 
      array (
        'value' => 0,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesInstaller' => 
  array (
    'class' => 'Mouf\\Services\\PackagesInstaller',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'config',
        'value' => 'REPOSITORY_PATH',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'packagesMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'Other packages',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'pageDsiplayer' => 
  array (
    'class' => 'Mouf\\Widgets\\PageDisplayer',
    'external' => false,
    'weak' => false,
  ),
  'phpVarsCheckRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\PhpVarsCheckRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'splashDefaultRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'psr.errorLogLogger' => 
  array (
    'class' => 'Mouf\\Utils\\Log\\Psr\\ErrorLogLogger',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'warning',
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'rendererCacheService' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\InMemoryCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'chainWith' => 'apcCacheService',
    ),
  ),
  'requiredValidator' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\RequiredValidator',
    'external' => false,
    'weak' => false,
  ),
  'rootController' => 
  array (
    'class' => 'Mouf\\Controllers\\RootController',
    'external' => false,
    'fieldBinds' => 
    array (
      'template' => 'bootstrapTemplate',
      'content' => 'block.content',
      'http404Handler' => 'httpErrorsController',
      'documentationMenu' => 'documentationMenu',
      'navBar' => 'navBar',
      'versionsMenuItem' => 'versionsMenuItem',
      'packagesMenuItem' => 'packagesMenuItem',
      'packageExporer' => 'packageExplorer',
      'logoHolder' => 'block.logoHolder',
    ),
    'fieldProperties' => 
    array (
      'repositoryPath' => 
      array (
        'type' => 'config',
        'value' => 'REPOSITORY_PATH',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'sectionBuilder' => 
  array (
    'class' => 'Mouf\\Services\\SectionBuilder',
    'external' => false,
    'weak' => false,
  ),
  'sessionManager' => 
  array (
    'class' => 'Mouf\\Utils\\Session\\SessionManager\\DefaultSessionManager',
    'external' => false,
  ),
  'splash' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Splash',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'whoopsMiddleware',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
    'weak' => false,
  ),
  'splashCacheApc' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\ApcCache',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'fallback' => 'splashCacheFile',
    ),
    'fieldProperties' => 
    array (
      'prefix' => 
      array (
        'type' => 'config',
        'value' => 'ROOT_URL',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashCacheFile' => 
  array (
    'class' => 'Mouf\\Utils\\Cache\\FileCache',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'cacheDirectory' => 
      array (
        'value' => 'splashCache/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'prefix' => 
      array (
        'type' => 'config',
        'value' => 'ROOT_URL',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashDefaultRouter' => 
  array (
    'class' => 'Mouf\\Mvc\\Splash\\Routers\\SplashDefaultRouter',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'notFoundRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'splashCacheApc',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'splashTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/mvc.splash-common/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'splashBrowserLanguageDetection',
    ),
  ),
  'twigEnvironment' => 
  array (
    'class' => 'Mouf\\Html\\Renderer\\Twig\\MoufTwigEnvironment',
    'external' => false,
    'weak' => false,
  ),
  'uRLValidatorFtpHttps' => 
  array (
    'class' => 'Mouf\\Utils\\Common\\Validators\\URLValidator',
    'external' => false,
    'weak' => false,
    'fieldProperties' => 
    array (
      'allowFtp' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      'allowHttps' => 
      array (
        'value' => true,
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'userMessageService' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\MessageService\\Service\\SessionMessageService',
    'external' => false,
    'weak' => false,
    'fieldBinds' => 
    array (
      'sessionManager' => 'sessionManager',
    ),
  ),
  'validatorsBrowserLanguageDetection' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Language\\BrowserLanguageDetection',
    'external' => false,
  ),
  'validatorsTranslateService' => 
  array (
    'class' => 'Mouf\\Utils\\I18n\\Fine\\Translate\\FinePHPArrayTranslationService',
    'external' => false,
    'fieldProperties' => 
    array (
      'i18nMessagePath' => 
      array (
        'value' => 'vendor/mouf/utils.common.validators/src/resources/',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
    'setterBinds' => 
    array (
      'setLanguageDetection' => 'validatorsBrowserLanguageDetection',
    ),
  ),
  'versionsMenuItem' => 
  array (
    'class' => 'Mouf\\Html\\Widgets\\Menu\\MenuItem',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'type' => 'string',
        'value' => 'Browse version',
        'parametertype' => 'primitive',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => NULL,
        'parametertype' => 'primitive',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 
        array (
        ),
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
  'whoopsMiddleware' => 
  array (
    'class' => 'Whoops\\StackPhp\\WhoopsMiddleWare',
    'external' => false,
    'weak' => false,
    'constructor' => 
    array (
      0 => 
      array (
        'value' => 'exceptionRouter',
        'parametertype' => 'object',
        'type' => 'string',
        'metadata' => 
        array (
        ),
      ),
      1 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
      2 => 
      array (
        'value' => 'DEBUG',
        'parametertype' => 'primitive',
        'type' => 'config',
        'metadata' => 
        array (
        ),
      ),
    ),
  ),
));


unset($moufManager);

/**
 * This is the base class of the Manage Object User Friendly or Modular object user framework (MOUF) framework.
 * This object can be used to get the objects manage by MOUF.
 *
 */
class Mouf {
	public function getClosures() {
		return [
		];
	}
	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getApcCacheService() {
	 	return MoufManager::getMoufManager()->get('apcCacheService');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_content() {
	 	return MoufManager::getMoufManager()->get('block.content');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_footer() {
	 	return MoufManager::getMoufManager()->get('block.footer');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_header() {
	 	return MoufManager::getMoufManager()->get('block.header');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_left() {
	 	return MoufManager::getMoufManager()->get('block.left');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_logoHolder() {
	 	return MoufManager::getMoufManager()->get('block.logoHolder');
	 }

	/**
	 * @return Mouf\Html\HtmlElement\HtmlBlock
	 */
	 public static function getBlock_right() {
	 	return MoufManager::getMoufManager()->get('block.right');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getBootstrapRenderer() {
	 	return MoufManager::getMoufManager()->get('bootstrapRenderer');
	 }

	/**
	 * @return Mouf\Html\Template\BootstrapTemplate
	 */
	 public static function getBootstrapTemplate() {
	 	return MoufManager::getMoufManager()->get('bootstrapTemplate');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getCustomRenderer() {
	 	return MoufManager::getMoufManager()->get('customRenderer');
	 }

	/**
	 * @return Mouf\Dao\DaoFactory
	 */
	 public static function getDaoFactory() {
	 	return MoufManager::getMoufManager()->get('daoFactory');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getDefaultLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('defaultLanguageDetection');
	 }

	/**
	 * @return Mouf\Html\Renderer\AutoChainRenderer
	 */
	 public static function getDefaultRenderer() {
	 	return MoufManager::getMoufManager()->get('defaultRenderer');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getDefaultTranslationService() {
	 	return MoufManager::getMoufManager()->get('defaultTranslationService');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibraryManager
	 */
	 public static function getDefaultWebLibraryManager() {
	 	return MoufManager::getMoufManager()->get('defaultWebLibraryManager');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\DefaultWebLibraryRenderer
	 */
	 public static function getDefaultWebLibraryRenderer() {
	 	return MoufManager::getMoufManager()->get('defaultWebLibraryRenderer');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\Menu
	 */
	 public static function getDocumentationMenu() {
	 	return MoufManager::getMoufManager()->get('documentationMenu');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\EmailValidator
	 */
	 public static function getEmailValidator() {
	 	return MoufManager::getMoufManager()->get('emailValidator');
	 }

	/**
	 * @return Mouf\Utils\Log\ErrorLogLogger
	 */
	 public static function getErrorLogLogger() {
	 	return MoufManager::getMoufManager()->get('errorLogLogger');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\ExceptionRouter
	 */
	 public static function getExceptionRouter() {
	 	return MoufManager::getMoufManager()->get('exceptionRouter');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getFileCacheService() {
	 	return MoufManager::getMoufManager()->get('fileCacheService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getFineCommonTranslationService() {
	 	return MoufManager::getMoufManager()->get('fineCommonTranslationService');
	 }

	/**
	 * @return Mouf\Modules\GoogleAnalytics\GoogleAnalyticsWebLibrary
	 */
	 public static function getGoogleAnalyticsWebLibrary() {
	 	return MoufManager::getMoufManager()->get('googleAnalyticsWebLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getHomeMenuItem() {
	 	return MoufManager::getMoufManager()->get('homeMenuItem');
	 }

	/**
	 * @return Mouf\Controllers\HomePageController
	 */
	 public static function getHomePageController() {
	 	return MoufManager::getMoufManager()->get('homePageController');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Controllers\HttpErrorsController
	 */
	 public static function getHttpErrorsController() {
	 	return MoufManager::getMoufManager()->get('httpErrorsController');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJQueryLibrary() {
	 	return MoufManager::getMoufManager()->get('jQueryLibrary');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_bootstrap() {
	 	return MoufManager::getMoufManager()->get('javascript.bootstrap');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getJavascript_highlight_js() {
	 	return MoufManager::getMoufManager()->get('javascript.highlight.js');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getLearnMenuItem() {
	 	return MoufManager::getMoufManager()->get('learnMenuItem');
	 }

	/**
	 * @return Mouf\Html\Utils\WebLibraryManager\WebLibrary
	 */
	 public static function getMessageServiceLibrary() {
	 	return MoufManager::getMoufManager()->get('messageServiceLibrary');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Widget\MessageWidget
	 */
	 public static function getMessageWidget() {
	 	return MoufManager::getMoufManager()->get('messageWidget');
	 }

	/**
	 * @return Mouf\Html\Template\Menus\BootstrapNavBar
	 */
	 public static function getNavBar() {
	 	return MoufManager::getMoufManager()->get('navBar');
	 }

	/**
	 * @return Mouf\Utils\Cache\NoCache
	 */
	 public static function getNoCacheService() {
	 	return MoufManager::getMoufManager()->get('noCacheService');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\NotFoundRouter
	 */
	 public static function getNotFoundRouter() {
	 	return MoufManager::getMoufManager()->get('notFoundRouter');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\NumericValidator
	 */
	 public static function getNumericValidatorDecimals() {
	 	return MoufManager::getMoufManager()->get('numericValidatorDecimals');
	 }

	/**
	 * @return Mouf\Services\PackageExplorer
	 */
	 public static function getPackageExplorer() {
	 	return MoufManager::getMoufManager()->get('packageExplorer');
	 }

	/**
	 * @return Mouf\Html\Renderer\FileBasedRenderer
	 */
	 public static function getPackageRenderer_moufhtml_widgets_messageservice() {
	 	return MoufManager::getMoufManager()->get('packageRenderer_mouf/html.widgets.messageservice');
	 }

	/**
	 * @return Mouf\Services\PackagesInstaller
	 */
	 public static function getPackagesInstaller() {
	 	return MoufManager::getMoufManager()->get('packagesInstaller');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getPackagesMenuItem() {
	 	return MoufManager::getMoufManager()->get('packagesMenuItem');
	 }

	/**
	 * @return Mouf\Widgets\PageDisplayer
	 */
	 public static function getPageDsiplayer() {
	 	return MoufManager::getMoufManager()->get('pageDsiplayer');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\PhpVarsCheckRouter
	 */
	 public static function getPhpVarsCheckRouter() {
	 	return MoufManager::getMoufManager()->get('phpVarsCheckRouter');
	 }

	/**
	 * @return Mouf\Utils\Log\Psr\ErrorLogLogger
	 */
	 public static function getPsr_errorLogLogger() {
	 	return MoufManager::getMoufManager()->get('psr.errorLogLogger');
	 }

	/**
	 * @return Mouf\Utils\Cache\InMemoryCache
	 */
	 public static function getRendererCacheService() {
	 	return MoufManager::getMoufManager()->get('rendererCacheService');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\RequiredValidator
	 */
	 public static function getRequiredValidator() {
	 	return MoufManager::getMoufManager()->get('requiredValidator');
	 }

	/**
	 * @return Mouf\Controllers\RootController
	 */
	 public static function getRootController() {
	 	return MoufManager::getMoufManager()->get('rootController');
	 }

	/**
	 * @return Mouf\Services\SectionBuilder
	 */
	 public static function getSectionBuilder() {
	 	return MoufManager::getMoufManager()->get('sectionBuilder');
	 }

	/**
	 * @return Mouf\Utils\Session\SessionManager\DefaultSessionManager
	 */
	 public static function getSessionManager() {
	 	return MoufManager::getMoufManager()->get('sessionManager');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Splash
	 */
	 public static function getSplash() {
	 	return MoufManager::getMoufManager()->get('splash');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getSplashBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('splashBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\Cache\ApcCache
	 */
	 public static function getSplashCacheApc() {
	 	return MoufManager::getMoufManager()->get('splashCacheApc');
	 }

	/**
	 * @return Mouf\Utils\Cache\FileCache
	 */
	 public static function getSplashCacheFile() {
	 	return MoufManager::getMoufManager()->get('splashCacheFile');
	 }

	/**
	 * @return Mouf\Mvc\Splash\Routers\SplashDefaultRouter
	 */
	 public static function getSplashDefaultRouter() {
	 	return MoufManager::getMoufManager()->get('splashDefaultRouter');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getSplashTranslateService() {
	 	return MoufManager::getMoufManager()->get('splashTranslateService');
	 }

	/**
	 * @return Mouf\Html\Renderer\Twig\MoufTwigEnvironment
	 */
	 public static function getTwigEnvironment() {
	 	return MoufManager::getMoufManager()->get('twigEnvironment');
	 }

	/**
	 * @return Mouf\Utils\Common\Validators\URLValidator
	 */
	 public static function getURLValidatorFtpHttps() {
	 	return MoufManager::getMoufManager()->get('uRLValidatorFtpHttps');
	 }

	/**
	 * @return Mouf\Html\Widgets\MessageService\Service\SessionMessageService
	 */
	 public static function getUserMessageService() {
	 	return MoufManager::getMoufManager()->get('userMessageService');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Language\BrowserLanguageDetection
	 */
	 public static function getValidatorsBrowserLanguageDetection() {
	 	return MoufManager::getMoufManager()->get('validatorsBrowserLanguageDetection');
	 }

	/**
	 * @return Mouf\Utils\I18n\Fine\Translate\FinePHPArrayTranslationService
	 */
	 public static function getValidatorsTranslateService() {
	 	return MoufManager::getMoufManager()->get('validatorsTranslateService');
	 }

	/**
	 * @return Mouf\Html\Widgets\Menu\MenuItem
	 */
	 public static function getVersionsMenuItem() {
	 	return MoufManager::getMoufManager()->get('versionsMenuItem');
	 }

	/**
	 * @return Whoops\StackPhp\WhoopsMiddleWare
	 */
	 public static function getWhoopsMiddleware() {
	 	return MoufManager::getMoufManager()->get('whoopsMiddleware');
	 }

}
?>
