<?php
/*
 * This file has been automatically generated by TDBM.
 * DO NOT edit this file, as it might be overwritten.
 */

namespace Mouf\Dao;

/**
 * The DaoFactory provides an easy access to all DAOs generated by TDBM.
 *
 * @Component
 */
class DaoFactory
{
}
